name: MassiveChannels
version: 2.13.0-SNAPSHOT
main: net.graystone.java.channels
description: <aqua>MassiveChannels <i>was developed by <pink>Flashera <i>and <pink>Ironhippy <i>for the purpose of implementing a multi-channel chat system specifically for roleplay servers.
website: http://gray-stone.net
authors: [Ironhippy, Flashera]
depend: [MassiveCore]
softdepend: [PermissionsEx, Factions]
permissions:
  massivechannels.default.focus: {description: focus a chat channel, default: true}
  massivechannels.default.info: {description: read information on a chat channel, default: true}
  massivechannels.default.list: {description: list usable chat channels, default: true}
  massivechannels.default.ignore: {description: ignore a player, default: true}
  massivechannels.default.listen: {description: listen to a chat channel, default: true}
  massivechannels.default.pm: {description: pm a player, default: true}
  massivechannels.default.me: {description: emote messages, default: op}
  massivechannels.default.leave: {description: leave a chat channel, default: op}
  massivechannels.nicknames.use: {description: set your own nickname, default: true}
  massivechannels.nicknames.set: {description: change another displayName, default: op}
  massivechannels.nicknames.prefixes: {description: set a user prefix, default: false}
  massivechannels.admin.create: {description: create a chat channel, default: op}
  massivechannels.admin.remove: {description: remove a chat channel, default: op}
  massivechannels.admin.staffdesc: {description: set staff description, default: op}
  massivechannels.admin.color: {description: use staff color in chat, default: op}
#---------------------------------------------------#
# ALL NOTATION
#---------------------------------------------------#
  massivechannels.*:
    children:
      massivechannels.default.focus: true
      massivechannels.default.info: true
      massivechannels.default.list: true
      massivechannels.default.ignore: true
      massivechannels.default.listen: true
      massivechannels.default.pm: true
      massivechannels.default.me: true
      massivechannels.default.leave: true
      massivechannels.nicknames.use: true
      massivechannels.nicknames.set: true
      massivechannels.nicknames.prefixes: true
      massivechannels.admin.create: true
      massivechannels.admin.remove: true
      massivechannels.admin.staffdesc: true
      massivechannels.admin.color: true
  massivechannels.admin:
    default: op
    children:
      massivechannels.*: true
#---------------------------------------------------#
# DEF PERMISSIONS
#---------------------------------------------------#
  massivechannels.default:
    default: true
    children:
      massivechannels.default.focus: true
      massivechannels.default.info: true
      massivechannels.default.list: true
      massivechannels.default.ignore: true
      massivechannels.default.listen: true
      massivechannels.default.pm: true
      massivechannels.default.me: true
      massivechannels.default.leave: true
      massivechannels.nicknames.use: true